//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserGuiWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParserGuiWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Web Parser.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelWord {
            get {
                return ResourceManager.GetString("CancelWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string GoWord {
            get {
                return ResourceManager.GetString("GoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images Count.
        /// </summary>
        public static string ImagesCount {
            get {
                return ResourceManager.GetString("ImagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log.
        /// </summary>
        public static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open results.
        /// </summary>
        public static string OpenResultsWord {
            get {
                return ResourceManager.GetString("OpenResultsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressHeader {
            get {
                return ResourceManager.GetString("ProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term.
        /// </summary>
        public static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point.
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
    }
}
